id: P00F16C07
initial_creation_type: ocr
source_metadata:
  volumes:
    1e5c7885cd2648f28c925192754cbacb:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ''
      total_pages: 1379
      volume_number: 37
